#!/usr/bin/env node
/**
 * MUDREXX provisioning script.
 *
 * This is the ONLY supported way to create the first Chief Admin account.
 * There is deliberately no runtime bootstrap route: nothing in the deployed
 * Worker can mint a SUPER_ADMIN without an existing Chief session.
 *
 * Usage:
 *   node scripts/seed.mjs --local
 *   node scripts/seed.mjs --remote
 *
 * Environment:
 *   CHIEF_EMAIL      (required)
 *   CHIEF_PASSWORD   (required, >= 10 chars, must satisfy the password policy)
 *   CHIEF_NAME       (optional, default "Chief Admin")
 *
 * What it does:
 *   1. Applies migrations/ to the target D1 database.
 *   2. Inserts the four canonical packages with monthly prices.
 *   3. Creates the Chief Admin account (SUPER_ADMIN) + admin profile.
 *
 * It never prints the password or the password hash.
 */

import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const DB_NAME = 'mudrexx_db';
const ITERATIONS = 210_000;
const KEY_LEN_BYTES = 32;
const SALT_LEN_BYTES = 16;

function b64url(bytes) {
  return Buffer.from(bytes).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

async function hashPassword(password) {
  const salt = crypto.getRandomValues(new Uint8Array(SALT_LEN_BYTES));
  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, [
    'deriveBits',
  ]);
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt, iterations: ITERATIONS, hash: 'SHA-256' },
    key,
    KEY_LEN_BYTES * 8,
  );
  return `PBKDF2-SHA256$${ITERATIONS}$${b64url(salt)}$${b64url(new Uint8Array(bits))}`;
}

function run(args, opts = {}) {
  return execFileSync('npx', args, { stdio: 'inherit', ...opts });
}

function main() {
  const target = process.argv.includes('--remote') ? '--remote' : '--local';
  const email = (process.env.CHIEF_EMAIL ?? '').trim().toLowerCase();
  const password = process.env.CHIEF_PASSWORD ?? '';
  const name = (process.env.CHIEF_NAME ?? 'Chief Admin').trim();

  if (!email || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
    console.error('CHIEF_EMAIL must be set to a valid email address.');
    process.exit(1);
  }
  if (password.length < 10 || !/[a-z]/.test(password) || !/[A-Z]/.test(password) || !/\d/.test(password)) {
    console.error('CHIEF_PASSWORD must be >= 10 chars and include lower, upper and digit.');
    process.exit(1);
  }

  console.log(`\n[1/3] Applying migrations to D1 (${target}) ...`);
  run(['wrangler', 'd1', 'migrations', 'apply', DB_NAME, target, '--config', 'wrangler.jsonc']);

  const tmp = mkdtempSync(join(tmpdir(), 'mudrexx-seed-'));
  const sqlPath = join(tmp, 'seed.sql');

  const chiefId = `usr_${crypto.randomUUID()}`;

  return hashPassword(password).then((hash) => {
    // Human IDs are allocated server-side at runtime; seed uses a documented fixed
    // Admin ID of 1000 for the first Chief so operators can recognise the account.
    const now = Date.now();
    const packages = [
      ['pkg_bronze', 'BRONZE', 'Bronze', 199900],
      ['pkg_silver', 'SILVER', 'Silver', 499900],
      ['pkg_gold', 'GOLD', 'Gold', 999900],
      ['pkg_entrepreneur', 'ENTREPRENEUR', 'Entrepreneur', 2499900],
    ];

    const sql = [
      '-- generated by scripts/seed.mjs',
      "INSERT OR IGNORE INTO users (id, human_id, email, password_hash, password_algo, role, status, full_name, first_name, last_name, payment_status, approval_status, is_demo, failed_attempts, created_at, updated_at)",
      `VALUES ('${chiefId}', '1000', '${email}', '${hash}', 'PBKDF2-SHA256', 'SUPER_ADMIN', 'ACTIVE', '${name.replace(/'/g, "''")}', '${name.split(/\s+/)[0].replace(/'/g, "''")}', '${name.split(/\s+/).slice(1).join(' ').replace(/'/g, "''")}', 'PENDING', 'PENDING', 0, 0, ${now}, ${now});`,
      "INSERT OR IGNORE INTO password_history (id, user_id, password_hash, created_at)",
      `VALUES ('pwd_${crypto.randomUUID()}', '${chiefId}', '${hash}', ${now});`,
      `INSERT OR IGNORE INTO admin_profiles (user_id, admin_id, business_name, created_at, updated_at)
       VALUES ('${chiefId}', '1000', 'MUDREXX', ${now}, ${now});`,
      `INSERT OR IGNORE INTO wallets (id, user_id, currency, balance_cents, frozen_cents, updated_at)
       VALUES ('wlt_${crypto.randomUUID()}', '${chiefId}', 'INR', 0, 0, ${now});`,
      ...packages.map(
        ([id, code, pkgName, price]) =>
          `INSERT OR IGNORE INTO packages (id, code, name, currency, is_active, limits_json, created_at, updated_at)
           VALUES ('${id}', '${code}', '${pkgName}', 'INR', 1, '{}', ${now}, ${now});
           INSERT OR IGNORE INTO package_prices (id, package_id, period, price_cents, currency, is_active)
           VALUES ('prc_${code.toLowerCase()}_monthly', '${id}', 'MONTHLY', ${price}, 'INR', 1);`,
      ),
      `INSERT OR IGNORE INTO settings (key, value_json, updated_at, updated_by)
       VALUES ('portal', '{"portalName":"MUDREXX","portalShortName":"MUDREXX","browserTitle":"MUDREXX Platform","loginTitle":"Sign in to MUDREXX","dashboardTitle":"Dashboard","footer":"MUDREXX — All rights reserved"}', ${now}, NULL);`,
    ].join('\n');

    writeFileSync(sqlPath, sql, { mode: 0o600 });

    console.log('\n[2/3] Seeding packages, portal settings and the Chief account ...');
    run(['wrangler', 'd1', 'execute', DB_NAME, target, '--config', 'wrangler.jsonc', '--file', sqlPath]);

    rmSync(tmp, { recursive: true, force: true });

    console.log('\n[3/3] Done.');
    console.log(`  target      : ${target}`);
    console.log(`  chief email : ${email}`);
    console.log(`  chief role  : SUPER_ADMIN`);
    console.log(`  admin id    : 1000`);
    console.log('\nNext steps:');
    console.log('  1. Set Worker secrets (see README.md §Secrets).');
    console.log('  2. Deploy: npm run deploy');
    console.log('  3. Seed AI skills: POST /api/ai/skills/seed (Chief session)');
    console.log('  4. Provision demo: POST /api/auth/demo');
    console.log('  5. Run the smoke test: node scripts/smoke.mjs --base-url https://<worker>.workers.dev');
  });
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
